### PR TITLE
Fix info_bar.hide() and some little cast problems

### PR DESCRIPTION
**Pull request by zzeroo**
Fix some compiler warnings and add the info_bar.hide() function,

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@zzeroo: Thanks for the PR! I update rustc version for appveyor and then I restart it. Sorry for the delay. :-/

@gkoz: we forgot to update appveyor version here. I open a PR ([done](https://github.com/gtk-rs/tests/pull/2)).

**Comment by gkoz** [comment]
If this code has casts problems it might be stale and need syncing with the tip of `examples/pending`.

**Comment by gkoz** [comment]
:+1:

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
